-- Legacy baseline retained for migration-history parity with the linked project.
-- The original media-processing schema was applied remotely before AuraFlow's
-- Supabase migration. `0002_auraflow_core.sql` preserves its data by renaming
-- conflicting tables before it creates the AuraFlow application schema.
