-- A client may write events generated by their own workspace actions and may
-- answer only review items addressed to them. Administrative workflow control
-- remains protected by the administrator policy from migration 0008.
create policy project_events_insert_owner on public.project_events for insert to authenticated with check (
  user_id = auth.uid() and actor_id = auth.uid() and public.owns_project(project_id)
);
create policy work_items_update_client_review on public.project_work_items for update to authenticated using (
  public.owns_project(project_id) and kind = 'review' and assigned_to = 'client'
) with check (
  public.owns_project(project_id) and kind = 'review' and assigned_to = 'client'
);
grant update on public.project_work_items to authenticated;
